/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50:  '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          900: '#1E3A8A',
        },
        ink: {
          DEFAULT: '#0D1117',
          soft:    '#1F2937',
          muted:   '#374151',
          subtle:  '#6B7280',
          faint:   '#9CA3AF',
          dark:    '#05070a',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          soft:    '#F8FAFC',
          muted:   '#F1F5F9',
          card:    '#FFFFFF',
          border:  '#E2E8F0',
        },
        accent: {
          DEFAULT: '#2563EB',
          soft:    '#EFF6FF',
          purple:  '#7C3AED',
          teal:    '#0D9488',
          orange:  '#EA580C',
        },
      },
      fontFamily: {
        display: ['var(--font-display)', 'sans-serif'],
        mono:    ['var(--font-mono)',    'monospace'],
        body:    ['var(--font-body)',    'sans-serif'],
      },
      boxShadow: {
        'card':       '0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.08), 0 16px 40px rgba(0,0,0,0.06)',
        'brand':      '0 4px 24px rgba(37,99,235,0.18)',
        'brand-lg':   '0 8px 40px rgba(37,99,235,0.25)',
        'glow':       '0 0 20px rgba(37,99,235,0.15)',
        'glow-lg':    '0 0 40px rgba(37,99,235,0.2)',
        'inner-glow': 'inset 0 0 20px rgba(37,99,235,0.05)',
      },
      animation: {
        'fade-up':      'fadeUp 0.6s ease forwards',
        'fade-in':      'fadeIn 0.5s ease forwards',
        'float':        'float 5s ease-in-out infinite',
        'pulse-dot':    'pulseDot 2s ease-in-out infinite',
        'marquee':      'marquee 28s linear infinite',
        'shimmer':      'shimmer 2.5s linear infinite',
        'slide-in-l':   'slideInLeft 0.7s cubic-bezier(0.23,1,0.32,1) forwards',
        'slide-in-r':   'slideInRight 0.7s cubic-bezier(0.23,1,0.32,1) forwards',
        'gradient':     'gradientShift 8s ease infinite',
        'border-glow':  'borderGlow 3s ease-in-out infinite',
        'text-reveal':  'textReveal 0.8s cubic-bezier(0.77,0,0.175,1) forwards',
        'scale-in':     'scaleIn 0.6s cubic-bezier(0.23,1,0.32,1) forwards',
        'rotate-in':    'rotateIn 0.8s cubic-bezier(0.23,1,0.32,1) forwards',
        'bounce-in':    'bounceIn 0.8s cubic-bezier(0.23,1,0.32,1) forwards',
        'wave':         'wave 2s ease-in-out infinite',
      },
      keyframes: {
        fadeUp:        { from: { opacity:0, transform:'translateY(24px)' }, to: { opacity:1, transform:'translateY(0)' } },
        fadeIn:        { from: { opacity:0 }, to: { opacity:1 } },
        float:         { '0%,100%': { transform:'translateY(0)' }, '50%': { transform:'translateY(-12px)' } },
        pulseDot:      { '0%,100%': { opacity:1, transform:'scale(1)' }, '50%': { opacity:0.5, transform:'scale(0.85)' } },
        marquee:       { '0%': { transform:'translateX(0)' }, '100%': { transform:'translateX(-50%)' } },
        shimmer:       { '0%': { backgroundPosition:'200% 0' }, '100%': { backgroundPosition:'-200% 0' } },
        slideInLeft:   { from: { opacity:0, transform:'translateX(-32px)' }, to: { opacity:1, transform:'translateX(0)' } },
        slideInRight:  { from: { opacity:0, transform:'translateX(32px)' }, to: { opacity:1, transform:'translateX(0)' } },
        gradientShift: { '0%': { backgroundPosition:'0% 50%' }, '50%': { backgroundPosition:'100% 50%' }, '100%': { backgroundPosition:'0% 50%' } },
        borderGlow:    { '0%,100%': { borderColor:'#BFDBFE', boxShadow:'0 0 8px rgba(37,99,235,0.1)' }, '50%': { borderColor:'#60A5FA', boxShadow:'0 0 20px rgba(37,99,235,0.2)' } },
        textReveal:    { from: { clipPath:'inset(0 100% 0 0)' }, to: { clipPath:'inset(0 0 0 0)' } },
        scaleIn:       { from: { opacity:0, transform:'scale(0.8)' }, to: { opacity:1, transform:'scale(1)' } },
        rotateIn:      { from: { opacity:0, transform:'rotate(-10deg) scale(0.9)' }, to: { opacity:1, transform:'rotate(0deg) scale(1)' } },
        bounceIn:      { '0%': { opacity:0, transform:'scale(0.3)' }, '50%': { transform:'scale(1.05)' }, '70%': { transform:'scale(0.95)' }, '100%': { opacity:1, transform:'scale(1)' } },
        wave:          { '0%,100%': { transform:'rotate(0deg)' }, '25%': { transform:'rotate(15deg)' }, '75%': { transform:'rotate(-15deg)' } },
      },
      transitionTimingFunction: {
        'spring':     'cubic-bezier(0.23,1,0.32,1)',
        'spring-bounce': 'cubic-bezier(0.34,1.56,0.64,1)',
        'smooth':     'cubic-bezier(0.16,1,0.3,1)',
      },
      transitionDuration: {
        '400': '400ms',
        '600': '600ms',
        '800': '800ms',
        '1200': '1200ms',
        '1500': '1500ms',
        '2000': '2000ms',
      },
    },
  },
  plugins: [],
}
